// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ShowNewBookmarkController from "./show_new_bookmark_controller"
application.register("show-new-bookmark", ShowNewBookmarkController)
